autoluz/ambientes/urls.py
from django.conf.urls import url

from autoluz.ambientes.views import new, dispositivos

urlpatterns = [
    url(r'^$', new, name='ambientes'),
    url(r'^(?P<id>[0-9]+)/$', dispositivos, name='dispositivos'),
]

autoluz/dispositivos/urls.py
from django.conf.urls import url

from autoluz.dispositivos.views import update

urlpatterns = [
    url(r'^(?P<id>[0-9]+)/$', update, name='update'),
]

autoluz/login/urls.py
from django.conf.urls import url

from autoluz.login.views import new, call_logout

urlpatterns = [
    url(r'^$', new, name='login'),
    url(r'^logout/$', call_logout, name='logout'),
]

autoluz/permissoes/urls.py
from django.conf.urls import url

from autoluz.ambientes.views import new, update

urlpatterns = [
    url(r'^$', new, name='ambientes'),
    url(r'^(?P<id>[0-9]+)/$', update, name='update'),
]

autoluz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from autoluz.core.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/', include('autoluz.login.urls', namespace='login')),
    url(r'^ambientes/', include('autoluz.ambientes.urls', namespace='ambientes')),
    url(r'^dispositivos/', include('autoluz.dispositivos.urls', namespace='dispositivos')),

    url(r'^admin/', admin.site.urls),
]

autoluz/ambientes/models.py
from django.db import models


class Ambiente(models.Model):
    name = models.CharField('nome', max_length=255)
    created_at = models.DateTimeField('criado em', auto_now_add = True)

    class Meta:
        verbose_name_plural = 'ambientes'
        verbose_name = 'ambiente'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

autoluz/dispositivos/models.py
from django.db import models

from autoluz.ambientes.models import Ambiente


class Dispositivo(models.Model):
    name = models.CharField('nome', max_length=255)
    ambiente = models.ForeignKey(Ambiente, verbose_name='Ambiente')
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField('criado em', auto_now_add = True)

    class Meta:
        verbose_name_plural = 'dispositivos'
        verbose_name = 'dispositivo'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

autoluz/permissoes/models.py
from django.db import models

from autoluz.dispositivos.models import Dispositivo
from django.contrib.auth.models import User


class Permissoes(models.Model):
    usuario = models.ForeignKey(User, verbose_name='Usuario')
    dispositivo = models.ForeignKey(Dispositivo, verbose_name='Dispositivo')
    created_at = models.DateTimeField('criado em', auto_now_add = True)

    class Meta:
        verbose_name_plural = 'dispositivos'
        verbose_name = 'dispositivo'
        ordering = ('-created_at',)

autoluz/dispositivos/forms.py
from django import forms

from autoluz.dispositivos.models import Dispositivo

class DispositivoForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Nome')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Senha')

autoluz/login/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Nome')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Senha')

autoluz/ambientes/views.py
from django.shortcuts import render

from autoluz.dispositivos.models import Dispositivo
from autoluz.ambientes.models import Ambiente
from autoluz.permissoes.models import Permissoes


def new(request):
    ambientes = Ambiente.objects.all().order_by('-created_at')
    return render(request, 'ambientes/ambientes-form.html', {'ambientes': ambientes})


def dispositivos(request, id):
    dispositivos = Dispositivo.objects.filter(ambiente__pk=id)
    permissoes = Permissoes.objects.filter(usuario__pk=request.user.pk)
    dispositivos_ids = [permissao.dispositivo.id for permissao in permissoes]
    disp = []
    for dispositivo in dispositivos:
        dispositivo = dispositivo.__dict__
        if dispositivo["id"] in dispositivos_ids:
            dispositivo["permission"] = True
        else:
            dispositivo["permission"] = False
        disp.append(dispositivo)

    return render(request, 'ambientes/ambientes-dispositivos.html', {'dispositivos': disp})

autoluz/core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url as r


def home(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(r('login:login'))
    else:
        return HttpResponseRedirect(r('ambientes:ambientes'))

autoluz/dispositivos/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from autoluz.dispositivos.models import Dispositivo


def update(request, id):
    dispositivos = Dispositivo.objects.get(pk=id)
    if dispositivos.status:
        dispositivos.status = False
    else:
        dispositivos.status = True
    dispositivos.save()
    ambiente_id = dispositivos.ambiente.id
    return HttpResponseRedirect(reverse('ambientes:dispositivos',  args=(ambiente_id,)))

autoluz/login/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r

from autoluz.login.forms import LoginForm


def new(request):
    if not request.user.is_authenticated():
        if request.method == 'POST':
            return create(request)
        return empty_form(request)
    else:
        return call_cms(request)


def create(request):
    form = LoginForm(request.POST)

    if not form.is_valid():
        return render(request, 'login/login.html', {'form': form})

    user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

    if user is not None:
        login(request, user)
        return call_cms(request)
    else:
        return render(request, 'login/login.html', {'form': form})


def empty_form(request):
    return render(request, 'login/login.html', {'form': LoginForm()})


def call_cms(request):
    return HttpResponseRedirect(r('home'))


def call_logout(request):
    logout(request)
    return HttpResponseRedirect(r('login:login'))

autoluz/permissoes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r

from autoluz.ambientes.models import Ambiente

LIST_ALUNO = ['sala_de_aula']
LIST_PROF = ['sala_de_aula', 'sala_dos_professores']
LIST_ADM = ['sala_de_aula', 'sala_dos_professores', 'corredor']

def new(request):
    ambientes = Ambiente.objects.all().order_by('-created_at')
    contenxt = []
    for ambiente in ambientes:
        ambiente = ambiente.__dict__
        #import ipdb; ipdb.set_trace()
        if request.user.groups.filter(name='aluno').exists() and ambiente['type'] in LIST_ALUNO:
            ambiente['visible'] = True
        elif request.user.groups.filter(name='professor').exists() and ambiente['type'] in LIST_PROF:
            ambiente['visible'] = True
        elif request.user.groups.filter(name='administrador').exists() and ambiente['type'] in LIST_ADM:
            ambiente['visible'] = True
        else:
            ambiente['visible'] = False
        contenxt.append(ambiente)
    return render(request, 'ambientes/ambientes-form.html', {'ambientes': contenxt})


def update(request, id):
    ambiente = Ambiente.objects.get(pk=id)
    if ambiente.status:
        ambiente.status = False
    else:
        ambiente.status = True
    ambiente.save()
    return new(request)

autoluz/ambientes/templates/ambientes/ambientes-dispositivos.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link href="{% static 'css/form-ambientes.css' %}" rel="stylesheet" />
{% endblock style %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Dispositivos</h1>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        {% for dispositivo in dispositivos %}
            <div class="cl-inline">
                <label class="cl-label-size">{{ dispositivo.name }} - </label>
                {% if dispositivo.status %}
                <a class="btn btn-default" href="{% url 'dispositivos:update' dispositivo.id %}" role="button">Ligar</a>
                {% else %}
                <a class="btn btn-default" href="{% url 'dispositivos:update' dispositivo.id %}" role="button">Desligar</a>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

autoluz/ambientes/templates/ambientes/ambientes-form.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link href="{% static 'css/form-ambientes.css' %}" rel="stylesheet" />
{% endblock style %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Controlador</h1>
        {% for ambiente in ambientes %}
            <a href="{% url 'ambientes:dispositivos' ambiente.id %}">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 cl-block cl-apagada">
                    <h3 class="text-center"><strong>{{ ambiente.name }}</strong></h3>
                </div>
            </a>
        {% endfor %}
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

autoluz/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Auto Luz{% endblock title %}</title>

	<link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/base.css' %}" rel="stylesheet" />

    {% block style %}
    {% endblock style %}

</head>
<body>
	<div class="container-fluid" id="jqHome">
	<!-- MENU -->
	 <nav class="navbar navbar-default navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a href="{% url 'home' %}" class="brand name-menu">Auto Luz</a>

	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
		        <ul class="nav navbar-nav navbar-right">
                    {% if not request.user.is_authenticated %}
                         <li><a href="{% url 'login:login' %}">Login</a></li>
                    {% else %}
                        <li><a href="{% url 'login:logout' %}">Sair</a></li>
                    {% endif %}
		        </ul>
	        </div>
	      </div>
	    </nav>
	<!-- MENU -->

	<!-- INTRODUÇÃO -->
		<div class="row div-introducao">
			<div class="container">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<a href="{% url 'home' %}" class="brand logo-menu"><h1><strong>Auto Luz</strong></h1></a>
				</div>
			</div>
			<div class="div-sub">
				<div class="container">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<h2>Iluminação Automatizada</h2>
					</div>
				</div>
			</div>
		</div>
	<!-- INTRODUÇÃO -->
        {% block content %}
        {% endblock content %}

	<!-- RODAPÉ -->
	<footer class="row div-rodape">
        <div class="container">
            <div class="div-conteudo">
                <nav>
                    <ul>
                        <li class="li-home"><a href="{% url 'home' %}">Home</a></li>
                        <li class="li-barra">|</li>
                        {% if not request.user.is_authenticated %}
                            <li><a href="{% url 'login:login' %}">Login</a></li>
                        {% else %}
							<li><a href="{% url 'login:logout' %}">Sair</a></li>
                        {% endif %}
                    </ul>
                </nav>
           </div>
        </div>
        <div class="div-copyright">
            <div class="container">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <p class="text-center">© 2017 Auto Luz - Iluminação Automatizada</p>
                </div>
            </div>
        </div>
	</footer>
	<!-- RODAPÉ -->

	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>

    {% block script %}
    {% endblock script %}

</body>
</html>

autoluz/core/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
{% endblock style %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

autoluz/core/templates/templates/login/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Login</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="post">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password.errors }}
                        {{ form.password }}
                 </div>
                    <input type="submit" class="btn btn-default" value="Entrar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}

autoluz/login/templates/login/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<!-- OVERVIEW -->
<div class="row">
    <div class="container">
        <h1>Login</h1>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
             <form method="post">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password.errors }}
                        {{ form.password }}
                 </div>
                    <input type="submit" class="btn btn-default" value="Entrar"/>
             </form>
        </div>
    </div>
</div>
<!-- OVERVIEW -->
{% endblock content %}